# validate YAML
# https://codebeautify.org/yaml-validator

name: github-actions
on:
  push:
jobs:
  build-check:
    name: build-check
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    steps:
      - uses: actions/checkout@v3
      # https://jekyllrb.com/docs/installation/ubuntu/
      - run: sudo apt-get update
      - run: sudo apt-get install -y ruby-full build-essential zlib1g-dev libxslt-dev libxml2-dev
      - run: sudo gem install jekyll bundler
      - run: sudo apt-get install -y libcurl4-openssl-dev aspell aspell-en
      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Bundle Environment
        run: bundle env
      - name: Install site dependencies
        run: bundle install
      - name: Build site
        run: bundle exec jekyll build --future
      - name: Check links
        run: bundle exec htmlproofer ./_site --only-4xx --enforce_https=false --ignore-urls="/vimeo.com/,/researchgate.net/"
      - name: Spellcheck
        run: ./spellcheck.sh
